var configJson = {
    "protein":{
        "glycosylation":{
        },   
        "phosphorylation":{
        },
        "glycation":{
        }
        ,"mutagenesis":{
        },
        "disease":{
        },
        "publication":{
        },
        "orthologs":{
        },
        "snv":{
        }
        ,"crossref":{
        },
        "site_annotation":{
        },
        "pro_annotation":{
        },
        "ptm_annotation":{
        },
        "function":{
        },
        "pathway":{
        },
        "reactions":{
        },
        "reaction_enzymes":{
        },
        "refseq":{
        },
        "mass":{
        }
        ,"uniprot":{
        }
        ,"protein_names":{
        }
        ,"gene_names":{
        }
        ,"species":{
        }
        ,"isoforms":{
        }
        ,"gene":{
        }
        ,"go_annotation":{
        }
        ,"expression_disease":{
        }
        ,"expression_tissue":{
        }
        ,"synthesized_glycans":{
        }
        ,"interactions":{
        }
    },
    "glycan":{
        "mass":{
        }
        ,"mass_pme":{
        }
        ,"iupac":{
        }
        ,"glycam":{
        }
        ,"glycoct":{
        }
        ,"inchi":{
        }
        ,"wurcs":{
        }
        ,"smiles_isomeric":{
        } 
        ,"inchi_key":{
        }
        ,"byonic":{
        }
        ,"gwb":{
        }
        ,"glycan_type":{
        }
        ,"missing_score":{
        }
        ,"number_monosaccharides":{
        }
        ,"fully_determined":{
        }
        ,"interactions":{
        }
        ,"expression":{
        }
        ,"subsumption":{
        }
        ,"names":{
        }
        ,"species":{
        }
        ,"glycoprotein":{
        }
        ,"enzyme":{
        }
        ,"residues":{
        }
        ,"motifs":{
        } 
        ,"classification":{
        }
        ,"composition":{
        }
        ,"crossref":{
        }
        ,"publication":{
        }
    }
};

