#!/bin/bash

SERVICE=`basename $0`
CFGFILE="${SERVICE}.cfg"
CIDFILE="${SERVICE}.cid"
LOGFILE="${SERVICE}.log"
. ${CFGFILE}

if [ "${ANALYTICS}" != "" ]; then
  ANALYTICS="--env WEBSERVICE_BASIC_GOOGLE_ANALYTICS_TAG_ID=${ANALYTICS}"
fi

start() {
	echo -n "Starting ${SERVICE}: "
	USER="`id -u`:`id -g`"
	docker pull "${IMAGE}" > "${LOGFILE}" 2>&1
        rm -f "${CIDFILE}"
	docker run --cidfile "${CIDFILE}" \
                   --env WEBSERVICE_BASIC_PORT=${PORT} \
                   --env WEBSERVICE_BASIC_MAX_CPU_CORE=${WORKERS:-1} \
                   ${ANALYTICS} \
                   ${EXTRA_ARGS} \
                   -u "${USER}" \
                   -p "${PORT}:${PORT}" \
                   "${IMAGE}" >> ${LOGFILE} 2>&1 &
	sleep 5
	echo `cat ${CIDFILE}`
}

stop() {
	echo -n "Shutting down ${SERVICE}: "
	docker kill `cat "${CIDFILE}"` && rm -f "${CIDFILE}"
}

status() {
	docker ps | fgrep -w ${IMAGE}
}

stats() {
	docker stats `cat ${CIDFILE}`
}

case "$1" in
    start)
	start
	status
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	status
	;;
    status)
	status
	;;
    stats)
	stats
	;;
    *)
	echo "Usage: $SERVICE {start|stop|restart|status|stats}"
	exit 1
	;;
esac
exit $RETVAL
